FROM centos:7 as builder
WORKDIR /app

RUN yum install -y wget

FROM scratch
WORKDIR /lib64
#### bash ####
COPY --from=builder /usr/lib64/libtinfo.so.5.9 /lib64/libtinfo.so.5
COPY --from=builder /usr/lib64/libdl-2.17.so /lib64/libdl.so.2
COPY --from=builder /usr/lib64/libc-2.17.so /lib64/libc.so.6
COPY --from=builder /usr/lib64/ld-2.17.so /lib64/ld-linux-x86-64.so.2
COPY --from=builder /usr/bin/bash /lib64
COPY --from=builder /usr/bin/wget /lib64

#### wget ####
COPY --from=builder /usr/lib64/libssl.so.1.0.2k /lib64/libssl.so.10
COPY --from=builder /usr/lib64/libcrypto.so.1.0.2k /lib64/libcrypto.so.10
COPY --from=builder /usr/lib64/libz.so.1.2.7 /lib64/libz.so.1
COPY --from=builder /usr/lib64/libdl-2.17.so /lib64/libdl.so.2
COPY --from=builder /usr/lib64/libidn.so.11.6.11 /lib64/libidn.so.11
COPY --from=builder /usr/lib64/libuuid.so.1.3.0 /lib64/libuuid.so.1
COPY --from=builder /usr/lib64/libpcre.so.1.2.0 /lib64/libpcre.so.1
COPY --from=builder /usr/lib64/libgssapi_krb5.so.2.2 /lib64/libgssapi_krb5.so.2
COPY --from=builder /usr/lib64/libkrb5.so.3.3 /lib64/libkrb5.so.3
COPY --from=builder /usr/lib64/libcom_err.so.2.1 /lib64/libcom_err.so.2
COPY --from=builder /usr/lib64/libk5crypto.so.3.1 /lib64/libk5crypto.so.3
COPY --from=builder /usr/lib64/libpthread-2.17.so /lib64/libpthread.so.0
COPY --from=builder /usr/lib64/libkrb5support.so.0.1 /lib64/libkrb5support.so.0
COPY --from=builder /usr/lib64/libkeyutils.so.1.5 /lib64/libkeyutils.so.1
COPY --from=builder /usr/lib64/libresolv-2.17.so /lib64/libresolv.so.2
COPY --from=builder /usr/lib64/libselinux.so.1 /lib64/libselinux.so.1

ENTRYPOINT ["/lib64/bash"]
